First Trial

It is a standalone custom layer and its testing, you can create and test it separately.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


class CustomLayer(nn.Module):
    def __init__(self, input_size, output_size):
        super(CustomLayer, self).__init__()
        self.weight = nn.Parameter(torch.rand(input_size, output_size))
        self.bias = nn.Parameter(torch.zeros(output_size))

    def forward(self, x):
        # Custom non-linear operation
        return torch.sin(x.mm(self.weight) + self.bias)


# Example usage to test the custom layer
input_size = 10
output_size = 5
batch_size = 3

# Create an instance of your custom layer
custom_layer = CustomLayer(input_size, output_size)

# Move the custom layer and input data to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
custom_layer.to(device)
input_data = torch.rand((batch_size, input_size)).to(device)

# Forward pass
output = custom_layer(input_data)

# Print the output
print("Output shape:", output.shape)
print("Output values:", output)

# Backward pass (gradient computation)
loss_function = nn.MSELoss()
target = torch.rand_like(output).to(device)
loss = loss_function(output, target)
loss.backward()

# Optimizer update (optional)
optimizer = optim.SGD(custom_layer.parameters(), lr=0.01)
optimizer.step()

# Check if the parameters of the custom layer have been updated
print("Custom layer weights:", custom_layer.weight)
print("Custom layer bias:", custom_layer.bias)

Output shape: torch.Size([3, 5])
Output values: tensor([[-0.4971, -0.4220, -0.6015, -0.5429, -0.1610],
        [ 0.4513,  0.0354, -0.2019, -0.4823, -0.0701],
        [ 0.6071,  0.3061,  0.7269,  0.7913,  0.5538]], grad_fn=<SinBackward0>)
Custom layer weights: Parameter containing:
tensor([[0.0220, 0.4254, 0.5066, 0.9658, 0.8950],
        [0.5781, 0.7742, 0.3002, 0.1466, 0.9577],
        [0.8081, 0.0510, 0.7395, 0.4055, 0.3747],
        [0.2891, 0.3215, 0.1348, 0.5786, 0.6693],
        [0.3701, 0.5491, 0.6556, 0.8324, 0.5624],
        [0.8002, 0.9016, 0.6168, 0.2295, 0.5702],
        [0.1859, 0.2443, 0.7709, 0.9012, 0.2784],
        [0.2160, 0.3964, 0.6990, 0.7154, 0.1217],
        [0.6104, 0.7239, 0.3413, 0.5432, 0.3181],
        [0.9878, 0.8646, 0.7643, 0.7098, 0.5338]], requires_grad=True)
Custom layer bias: Parameter containing:
tensor([-0.0019, -0.0016, -0.0021, -0.0029, -0.0024], requires_grad=True)


Second Trial

The code includes a simple training loop with a mean squared error loss and stochastic gradient descent optimizer.

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim


class CustomLayer(nn.Module):
    def __init__(self, input_size, output_size):
        super(CustomLayer, self).__init__()
        self.weight = nn.Parameter(torch.rand(input_size, output_size))
        self.bias = nn.Parameter(torch.zeros(output_size))

    def forward(self, x):
        # Custom non-linear operation
        return torch.sin(x.mm(self.weight) + self.bias)


# Example usage to train the custom layer
input_size = 10
output_size = 5
batch_size = 32
learning_rate = 0.01
epochs = 1000

# Create an instance of your custom layer
custom_layer = CustomLayer(input_size, output_size)

# Move the custom layer and input data to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
custom_layer.to(device)
input_data = torch.rand((batch_size, input_size)).to(device)
target = torch.rand((batch_size, output_size)).to(device)

# Define loss function and optimizer
loss_function = nn.MSELoss()
optimizer = optim.SGD(custom_layer.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    # Forward pass
    output = custom_layer(input_data)

    # Compute the loss
    loss = loss_function(output, target)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# Check the final parameters of the custom layer
print("Custom layer weights:", custom_layer.weight)
print("Custom layer bias:", custom_layer.bias)

Epoch 0, Loss: 0.41681012511253357
Epoch 100, Loss: 0.27911481261253357
Epoch 200, Loss: 0.23044569790363312
Epoch 300, Loss: 0.21271133422851562
Epoch 400, Loss: 0.20513923466205597
Epoch 500, Loss: 0.20134583115577698
Epoch 600, Loss: 0.19897450506687164
Epoch 700, Loss: 0.19714219868183136
Epoch 800, Loss: 0.19552579522132874
Epoch 900, Loss: 0.19400539994239807
Custom layer weights: Parameter containing:
tensor([[0.1152, 0.1220, 0.1851, 0.4294, 0.8466],
        [0.1535, 0.5954, 0.6350, 0.5144, 0.2337],
        [0.6109, 0.4297, 0.3304, 0.2142, 0.1500],
        [0.6589, 0.1326, 0.4990, 0.3534, 0.4469],
        [0.4007, 0.7092, 0.6476, 0.1486, 0.6996],
        [0.8808, 0.7338, 0.1925, 0.7481, 0.0036],
        [0.8964, 0.4242, 0.7540, 0.5882, 0.4429],
        [0.2343, 0.5844, 0.6002, 0.0583, 0.6616],
        [0.6210, 0.5530, 0.4327, 0.8173, 0.2986],
        [0.5848, 0.5522, 0.1778, 0.6297, 0.1636]], requires_grad=True)
Custom layer bias: Parameter containing:
tensor([-0.1360, -0.2908, 

Third Trial

This code defines a custom neural network layer using PyTorch and demonstrates how to train it. Let's break down the code step by step:

1. **CustomLayer class definition:**
   - The `CustomLayer` class is a subclass of `nn.Module`, the base class for all PyTorch neural network modules.
   - It has an `__init__` method that initializes the layer with randomly initialized weights and zero biases. The weights and biases are stored as `nn.Parameter` objects, making them trainable during the optimization process.
   - The `forward` method defines the forward pass of the layer, applying a custom non-linear operation to the input `x`. In this case, it computes the sine of the matrix multiplication of `x` with the weights and adds the bias.

2. **Example usage to train the custom layer:**
   - It specifies the input size (`input_size`), output size (`output_size`), batch size (`batch_size`), learning rate (`learning_rate`), and the number of epochs (`epochs`).
   - Creates an instance of the `CustomLayer` with the specified input and output sizes.
   - Checks whether a GPU is available and moves the custom layer and input data to the GPU if possible.
   - Defines a mean squared error loss function (`nn.MSELoss`) and the stochastic gradient descent optimizer (`optim.SGD`) to update the parameters during training.

3. **Training loop:**
   - Iterates through the specified number of epochs.
   - Performs a forward pass through the custom layer.
   - Computes the mean squared error loss between the predicted output and the target.
   - Performs a backward pass to compute gradients and updates the model parameters using stochastic gradient descent.

4. **Prints the loss every 100 epochs during training.**

5. **After training, it prints the final parameters of the custom layer (weights and biases).**

In summary, this code demonstrates the creation and training of a custom neural network layer using PyTorch, where the layer applies a non-linear operation (sine function) to the input data during the forward pass. The training is performed using mean squared error loss and stochastic gradient descent.

This code now includes additional checks for input validation, parameter initialization, and device compatibility
and checks for unexpected forward pass output, invalid loss values, and NaN values in model parameters during each iteration of the training loop. If any of these issues are detected, warning messages will be printed.

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim


class CustomLayer(nn.Module):
    def __init__(self, input_size, output_size):
        super(CustomLayer, self).__init__()

        # Input validation
        if (
            not isinstance(input_size, int)
            or not isinstance(output_size, int)
            or input_size <= 0
            or output_size <= 0
        ):
            raise ValueError("Invalid input or output size.")

        # Parameter initialization
        self.weight = nn.Parameter(torch.rand(input_size, output_size))
        self.bias = nn.Parameter(torch.zeros(output_size))

        # Check parameter shapes
        if self.weight.size() != (input_size, output_size) or self.bias.size() != (
            output_size,
        ):
            print("Warning: Incorrect parameter initialization.")

    def forward(self, x):
        # Custom non-linear operation
        return torch.sin(x.mm(self.weight) + self.bias)


# Example usage to train the custom layer
input_size = 10
output_size = 5
batch_size = 32
learning_rate = 0.01
epochs = 1000

# Create an instance of your custom layer
custom_layer = CustomLayer(input_size, output_size)

# Move the custom layer and input data to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
custom_layer.to(device)
input_data = torch.rand((batch_size, input_size)).to(device)
target = torch.rand((batch_size, output_size)).to(device)

# Define loss function and optimizer
loss_function = nn.MSELoss()
optimizer = optim.SGD(custom_layer.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    # Forward pass
    output = custom_layer(input_data)

    # Additional checks
    if not torch.is_tensor(output) or output.size() != (batch_size, output_size):
        print("Warning: Unexpected forward pass output.")

    # Compute the loss
    loss = loss_function(output, target)

    # Additional checks
    if not torch.is_tensor(loss) or loss.dim() != 0:
        print("Warning: Invalid loss value.")

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()

    # Additional checks
    optimizer.step()
    if any(torch.isnan(param).any() for param in custom_layer.parameters()):
        print("Warning: NaN values detected in model parameters.")

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# Check the final parameters of the custom layer
print("Custom layer weights:", custom_layer.weight)
print("Custom layer bias:", custom_layer.bias)

Epoch 0, Loss: 0.2725360691547394
Epoch 100, Loss: 0.23698008060455322
Epoch 200, Loss: 0.2238324135541916
Epoch 300, Loss: 0.21788565814495087
Epoch 400, Loss: 0.2145886868238449
Epoch 500, Loss: 0.21240290999412537
Epoch 600, Loss: 0.21073603630065918
Epoch 700, Loss: 0.20933374762535095
Epoch 800, Loss: 0.20807668566703796
Epoch 900, Loss: 0.20690453052520752
Custom layer weights: Parameter containing:
tensor([[ 0.8275,  0.7250,  0.2966,  0.7577,  0.5092],
        [ 0.4686,  0.8673,  0.0864,  0.8612,  0.2449],
        [ 0.4059,  0.6153,  0.2913,  0.7620,  0.6555],
        [ 0.4160,  0.2468,  0.4900, -0.0017,  0.6629],
        [ 0.8212,  0.3362,  0.8577,  0.5394,  0.4457],
        [ 0.2779,  0.3074,  0.2047,  0.3181,  0.6938],
        [ 0.6295,  0.2011,  0.3845,  0.5593,  0.1593],
        [ 0.3796,  0.3657,  0.5580, -0.0296,  0.6510],
        [ 0.2780,  0.7183,  0.6741,  0.3820,  0.0278],
        [-0.0870,  0.1265,  0.6052,  0.3348,  0.0417]], requires_grad=True)
Custom layer bias: P

Last Trial

Now, the train_model function takes a model, input data, target, loss function, optimizer, and a list of additional checks as arguments. This makes the code more generic and allows you to easily apply the same training logic to different layers or models. The check_output_size, check_loss_value, and check_nan_parameters functions are examples of additional checks that can be applied during training.

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim


def train_model(
    model, input_data, target, loss_function, optimizer, epochs, additional_checks=None
):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    input_data = input_data.to(device)
    target = target.to(device)

    for epoch in range(epochs):
        # Forward pass
        output = model(input_data)

        # Additional checks
        if additional_checks is not None:
            for check in additional_checks:
                check(output, target, model)

        # Compute the loss
        loss = loss_function(output, target)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()

        # Additional checks
        optimizer.step()
        if additional_checks is not None:
            for check in additional_checks:
                check(output, target, model)

        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss.item()}")


# Example usage for the generic training function with a custom layer
class CustomLayer(nn.Module):
    def __init__(self, input_size, output_size):
        super(CustomLayer, self).__init__()
        self.weight = nn.Parameter(torch.rand(input_size, output_size))
        self.bias = nn.Parameter(torch.zeros(output_size))

    def forward(self, x):
        return torch.sin(x.mm(self.weight) + self.bias)


# Additional check functions
def check_output_size(output, target, model):
    if not torch.is_tensor(output) or output.size() != target.size():
        print("Warning: Unexpected forward pass output size.")


def check_loss_value(output, target, model):
    loss_function = nn.MSELoss()
    loss = loss_function(output, target)
    if not torch.is_tensor(loss) or loss.dim() != 0:
        print("Warning: Invalid loss value.")


def check_nan_parameters(output, target, model):
    if any(torch.isnan(param).any() for param in model.parameters()):
        print("Warning: NaN values detected in model parameters.")


# Example usage to train the custom layer with generic training function
input_size = 10
output_size = 5
batch_size = 32
learning_rate = 0.01
epochs = 1000

custom_layer = CustomLayer(input_size, output_size)

input_data = torch.rand((batch_size, input_size))
target = torch.rand((batch_size, output_size))

optimizer = optim.SGD(custom_layer.parameters(), lr=learning_rate)

additional_checks = [check_output_size, check_loss_value, check_nan_parameters]

train_model(
    custom_layer, input_data, target, nn.MSELoss(), optimizer, epochs, additional_checks
)

# Check the final parameters of the custom layer
print("Custom layer weights:", custom_layer.weight)
print("Custom layer bias:", custom_layer.bias)

Epoch 0, Loss: 0.4442346692085266
Epoch 100, Loss: 0.3049066662788391
Epoch 200, Loss: 0.2576864957809448
Epoch 300, Loss: 0.23753777146339417
Epoch 400, Loss: 0.2236039638519287
Epoch 500, Loss: 0.2116963118314743
Epoch 600, Loss: 0.20289433002471924
Epoch 700, Loss: 0.19736634194850922
Epoch 800, Loss: 0.19367939233779907
Epoch 900, Loss: 0.1907043606042862
Custom layer weights: Parameter containing:
tensor([[ 0.5380,  0.7821,  0.2931,  0.3747,  0.1308],
        [ 0.1686, -0.0026,  0.0795,  0.2055,  0.0280],
        [ 0.4638,  0.6330,  0.1474,  0.2454,  0.6370],
        [ 0.7677,  0.4780,  0.7362,  0.7217,  0.3613],
        [ 0.0388,  0.1295,  0.8411,  0.8618,  0.0249],
        [ 0.8336,  0.7655,  0.7907,  0.7028,  0.3246],
        [ 0.6012,  0.2898,  0.7524,  0.6763,  0.7260],
        [ 0.5308,  0.7941,  0.3912,  0.0096, -0.1027],
        [ 0.6180,  0.2837,  0.3156,  0.5001, -0.1638],
        [ 0.5713,  0.8290,  0.6917,  0.5471, -0.0986]], requires_grad=True)
Custom layer bias: Para